export const MEMBERS = [
  { name: "MATI", position: "Position", twitterHandle: "@test", link: "/" },
  { name: "test", position: "Position", twitterHandle: "@test", link: "/" },
  { name: "PAULA", position: "Position", twitterHandle: "@test", link: "/" },
  {
    name: "DR GORILLA",
    position: "Position",
    twitterHandle: "@test",
    link: "/",
  },
  {
    name: "JABBERWOCK",
    position: "Position",
    twitterHandle: "@test",
    link: "/",
  },
  { name: "NG", position: "Position", twitterHandle: "@test", link: "/" },
  {
    name: "OXGORILLA",
    position: "Position",
    twitterHandle: "@test",
    link: "/",
  },
  { name: "ASHITAKA", position: "Position", twitterHandle: "@test", link: "/" },
  { name: "GAS1CENT", position: "Position", twitterHandle: "@test", link: "/" },
  { name: "GOTZEN", position: "Position", twitterHandle: "@test", link: "/" },
  { name: "UWUNT", position: "Position", twitterHandle: "@test", link: "/" },
  {
    name: "WEI3ERHASE",
    position: "Position",
    twitterHandle: "@test",
    link: "/",
  },
  { name: "PARTICLE", position: "Position", twitterHandle: "@test", link: "/" },
  { name: "PEPO", position: "Position", twitterHandle: "@test", link: "/" },
  {
    name: "SKELETOR",
    position: "Position",
    twitterHandle: "@test",
    link: "/",
  },
  { name: "SHAITO", position: "Position", twitterHandle: "@test", link: "/" },
  {
    name: "TURTLEMOJI",
    position: "Position",
    twitterHandle: "@test",
    link: "/",
  },
  { name: "0XARDY", position: "Position", twitterHandle: "@test", link: "/" },
  { name: "RBP", position: "Position", twitterHandle: "@test", link: "/" },
  { name: "JOXES", position: "Position", twitterHandle: "@test", link: "/" },
];
