export const MEMBERS = [
  {
    name: "MATI",
    position: "Position",
    twitter: "https://twitter.com/MatiasNisenson",
    github: "",
    description: "",
  },
  {
    name: "BILLI",
    position: "Position",
    twitter: "",
    github: "https://github.com/Billy-103",
    description: "",
  },
  {
    name: "PEPO",
    position: "Position",
    twitter: "https://twitter.com/0xPEPO",
    github: "https://github.com/vPEPO",
    description: "",
  },
  {
    name: "AUSTRIAN",
    position: "Position",
    twitter: "https://twitter.com/0xAustrian",
    github: "https://github.com/0xAustrian",
    description: "",
  },
  {
    name: "DR GORILLA",
    position: "Position",
    twitter: "https://twitter.com/DrGorilla_md",
    github: "https://github.com/drgorillamd",
    description: "",
  },
  {
    name: "JABBERWOCK",
    position: "Position",
    twitter: "https://twitter.com/0xGorillaDev",
    github: "https://github.com/0xJabberwock",
    description: "",
  },
  {
    name: "NG",
    position: "Position",
    twitter: "https://twitter.com/ngndev",
    github: "https://github.com/0xng",
    description: "",
  },
  {
    name: "OXGORILLA",
    position: "Position",
    twitter: "https://twitter.com/0xGorillaDev",
    github: "https://github.com/0xGorilla",
    description: "",
  },
  {
    name: "ASHITAKA",
    position: "Position",
    twitter: "https://twitter.com/0xAshitakah",
    github: "https://github.com/ashitakah",
    description: "",
  },
  {
    name: "GAS1CENT",
    position: "Position",
    twitter: "https://twitter.com/gas1cent",
    github: "https://github.com/gas1cent",
    description: "",
  },
  {
    name: "GOTZEN",
    position: "Position",
    twitter: "https://twitter.com/0xGotzen",
    github: "https://github.com/gotzenx",
    description: "",
  },
  {
    name: "WEI3ERHASE",
    position: "Position",
    twitter: "https://twitter.com/wei3erHase",
    github: "https://github.com/wei3erHase",
    description: "",
  },
  {
    name: "PARTI",
    position: "Position",
    twitter: "https://twitter.com/0xParticle",
    github: "https://github.com/0xParticle",
    description: "",
  },
  {
    name: "SKELETOR",
    position: "Position",
    twitter: "https://twitter.com/Skeletor_Space",
    github: "https://github.com/skeletor-spaceman",
    description: "",
  },
  {
    name: "SHAITO",
    position: "Position",
    twitter: "https://twitter.com/0xShaito",
    github: "https://github.com/0xShaito",
    description: "",
  },
  {
    name: "TURTLEMOJI",
    position: "Position",
    twitter: "",
    github: "https://github.com/turtlemoji",
    description: "",
  },
  {
    name: "ARDY",
    position: "Position",
    twitter: "https://twitter.com/0xArdy",
    github: "https://github.com/0xArdy",
    description: "",
  },
  {
    name: "RBP",
    position: "Position",
    twitter: "",
    github: "",
    description: "",
  },
  {
    name: "JOXES",
    position: "Position",
    twitter: "https://twitter.com/0xJoxes",
    github: "https://github.com/Joxess",
    description: "",
  },
  {
    name: "RACCON",
    position: "Position",
    twitter: "https://twitter.com/0xRaccoonDev",
    github: "https://github.com/0xRaccoon",
    description: "",
  },
  {
    name: "MONO",
    position: "Position",
    twitter: "https://twitter.com/0x_mono",
    github: "",
    description: "",
  },
];
